-- Hamburguesitas: esquema + políticas para MVP
-- En Supabase: SQL Editor -> pegar este archivo -> Run

create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  reviewer text not null,
  burger numeric(4,2),
  fries numeric(4,2),
  time numeric(4,2),
  venue numeric(4,2),
  packaging numeric(4,2),
  notes text,
  created_at timestamptz not null default now(),
  check (burger is null or burger between 0 and 10),
  check (fries is null or fries between 0 and 10),
  check (time is null or time between 0 and 10),
  check (venue is null or venue between 0 and 10),
  check (packaging is null or packaging between 0 and 10)
);

create index if not exists ratings_restaurant_id_idx on public.ratings(restaurant_id);

alter table public.restaurants enable row level security;
alter table public.ratings enable row level security;

-- MVP: app pública. Para producción conviene agregar Supabase Auth
-- y reemplazar estas policies por policies basadas en auth.uid().
drop policy if exists "public read restaurants" on public.restaurants;
drop policy if exists "public insert restaurants" on public.restaurants;
drop policy if exists "public update restaurants" on public.restaurants;
drop policy if exists "public read ratings" on public.ratings;
drop policy if exists "public insert ratings" on public.ratings;
drop policy if exists "public update ratings" on public.ratings;

create policy "public read restaurants" on public.restaurants for select using (true);
create policy "public insert restaurants" on public.restaurants for insert with check (true);
create policy "public update restaurants" on public.restaurants for update using (true) with check (true);

create policy "public read ratings" on public.ratings for select using (true);
create policy "public insert ratings" on public.ratings for insert with check (true);
create policy "public update ratings" on public.ratings for update using (true) with check (true);
