-- Hamburguesitas v2
-- Ejecutar en un proyecto Supabase NUEVO o, si reutilizás el anterior, borrar las tablas viejas primero.

create extension if not exists pgcrypto;

drop table if exists public.ratings cascade;
drop table if exists public.restaurants cascade;
drop table if exists public.profiles cascade;

drop type if exists public.app_role cascade;
create type public.app_role as enum ('user', 'editor', 'admin');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  role public.app_role not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image_url text,
  website_url text,
  instagram_url text,
  address text,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ratings (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  burger numeric(4,2),
  fries numeric(4,2),
  price_quality numeric(4,2),
  time numeric(4,2),
  venue numeric(4,2),
  packaging numeric(4,2),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (burger is null or burger between 0 and 10),
  check (fries is null or fries between 0 and 10),
  check (price_quality is null or price_quality between 0 and 10),
  check (time is null or time between 0 and 10),
  check (venue is null or venue between 0 and 10),
  check (packaging is null or packaging between 0 and 10)
);

create index ratings_restaurant_id_idx on public.ratings(restaurant_id);
create index ratings_user_id_idx on public.ratings(user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_updated_at before update on public.profiles
for each row execute procedure public.set_updated_at();
create trigger restaurants_updated_at before update on public.restaurants
for each row execute procedure public.set_updated_at();
create trigger ratings_updated_at before update on public.ratings
for each row execute procedure public.set_updated_at();

create or replace function public.is_editor_or_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('editor', 'admin')
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.restaurants enable row level security;
alter table public.ratings enable row level security;

-- Perfil: cada usuario puede leer/editar su propio perfil. El rol no debe cambiarse desde el frontend.
create policy "profiles own select" on public.profiles
for select to authenticated using (id = auth.uid());

-- No damos UPDATE sobre profiles desde el cliente: el rol se administra desde Supabase.

-- Restaurantes: cualquiera puede leer. Solo editor/admin puede crear y editar.
create policy "restaurants public read" on public.restaurants
for select to anon, authenticated using (true);

create policy "restaurants editor insert" on public.restaurants
for insert to authenticated
with check (public.is_editor_or_admin() and created_by = auth.uid());

create policy "restaurants editor update" on public.restaurants
for update to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

create policy "restaurants admin delete" on public.restaurants
for delete to authenticated
using (public.is_admin());

-- Evaluaciones: cualquiera puede leer. Un usuario autenticado puede crear/editar las propias.
create policy "ratings public read" on public.ratings
for select to anon, authenticated using (true);

create policy "ratings authenticated insert" on public.ratings
for insert to authenticated
with check (user_id = auth.uid());

create policy "ratings own update" on public.ratings
for update to authenticated
using (user_id = auth.uid() or public.is_editor_or_admin())
with check (user_id = auth.uid() or public.is_editor_or_admin());

create policy "ratings own delete" on public.ratings
for delete to authenticated
using (user_id = auth.uid() or public.is_admin());

-- Storage: bucket público para que las imágenes puedan verse sin login.
insert into storage.buckets (id, name, public)
values ('restaurant-images', 'restaurant-images', true)
on conflict (id) do update set public = true;

create policy "restaurant images public read"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'restaurant-images');

create policy "restaurant images editor upload"
on storage.objects for insert
to authenticated
with check (bucket_id = 'restaurant-images' and public.is_editor_or_admin());

create policy "restaurant images editor update"
on storage.objects for update
to authenticated
using (bucket_id = 'restaurant-images' and public.is_editor_or_admin())
with check (bucket_id = 'restaurant-images' and public.is_editor_or_admin());

create policy "restaurant images editor delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'restaurant-images' and public.is_editor_or_admin());
