-- Aprobación de cambios de hamburgueserías por administrador.
-- Ejecutar DESPUÉS de 001_initial_schema.sql y 003_rating_permissions.sql.

create table if not exists public.restaurant_requests (
  id bigint generated by default as identity primary key,
  restaurant_id bigint references public.restaurants(id) on delete cascade,
  request_type text not null check (request_type in ('create', 'update')),
  proposed_data jsonb not null,
  requested_by uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  reviewer_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (request_type = 'create' and restaurant_id is null)
    or
    (request_type = 'update' and restaurant_id is not null)
  )
);

create index if not exists restaurant_requests_status_idx
  on public.restaurant_requests(status, created_at desc);

create index if not exists restaurant_requests_requested_by_idx
  on public.restaurant_requests(requested_by, created_at desc);

create or replace function public.restaurant_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists restaurant_requests_updated_at on public.restaurant_requests;
create trigger restaurant_requests_updated_at
before update on public.restaurant_requests
for each row execute procedure public.restaurant_requests_updated_at();

alter table public.restaurant_requests enable row level security;

-- Los editores pueden crear solicitudes para sí mismos.
drop policy if exists "restaurant requests editor insert" on public.restaurant_requests;
create policy "restaurant requests editor insert"
on public.restaurant_requests
for insert
to authenticated
with check (
  requested_by = auth.uid()
  and public.is_editor_or_admin()
);

-- Cada editor ve sus propias solicitudes. El admin ve todas.
drop policy if exists "restaurant requests requester read" on public.restaurant_requests;
create policy "restaurant requests requester read"
on public.restaurant_requests
for select
to authenticated
using (
  requested_by = auth.uid()
  or public.is_admin()
);

-- Solo el admin puede modificar el estado de una solicitud.
drop policy if exists "restaurant requests admin update" on public.restaurant_requests;
create policy "restaurant requests admin update"
on public.restaurant_requests
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- A partir de ahora el editor NO modifica restaurants directamente.
drop policy if exists "restaurants editor insert" on public.restaurants;
drop policy if exists "restaurants editor update" on public.restaurants;

-- El admin conserva acceso directo.
drop policy if exists "restaurants admin insert" on public.restaurants;
create policy "restaurants admin insert"
on public.restaurants
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "restaurants admin update" on public.restaurants;
create policy "restaurants admin update"
on public.restaurants
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Aprueba o rechaza una solicitud de forma atómica.
-- Si es CREATE, crea la hamburguesería y opcionalmente su primera evaluación.
-- Si es UPDATE, aplica exactamente los datos propuestos.
create or replace function public.review_restaurant_request(
  p_request_id bigint,
  p_approve boolean,
  p_reviewer_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  req public.restaurant_requests%rowtype;
  restaurant_data jsonb;
  initial_rating jsonb;
  new_restaurant_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Solo un administrador puede revisar solicitudes';
  end if;

  select *
  into req
  from public.restaurant_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception 'Solicitud no encontrada';
  end if;

  if req.status <> 'pending' then
    raise exception 'La solicitud ya fue revisada';
  end if;

  if p_approve then
    restaurant_data := req.proposed_data -> 'restaurant';

    if req.request_type = 'create' then
      if nullif(btrim(restaurant_data ->> 'name'), '') is null then
        raise exception 'El nombre de la hamburguesería es obligatorio';
      end if;

      insert into public.restaurants (
        name,
        description,
        image_url,
        website_url,
        instagram_url,
        address,
        notes,
        created_by
      )
      values (
        restaurant_data ->> 'name',
        restaurant_data ->> 'description',
        restaurant_data ->> 'image_url',
        restaurant_data ->> 'website_url',
        restaurant_data ->> 'instagram_url',
        restaurant_data ->> 'address',
        restaurant_data ->> 'notes',
        req.requested_by
      )
      returning id into new_restaurant_id;

      initial_rating := req.proposed_data -> 'initial_rating';

      if initial_rating is not null
         and jsonb_typeof(initial_rating) = 'object'
         and coalesce((initial_rating ->> 'has_rating')::boolean, false) then
        if nullif(btrim(initial_rating ->> 'notes'), '') is null then
          raise exception 'La primera evaluación necesita un comentario';
        end if;

        insert into public.ratings (
          restaurant_id,
          user_id,
          burger,
          fries,
          price_quality,
          time,
          venue,
          packaging,
          notes
        )
        values (
          new_restaurant_id,
          req.requested_by,
          nullif(initial_rating ->> 'burger', '')::numeric,
          nullif(initial_rating ->> 'fries', '')::numeric,
          nullif(initial_rating ->> 'price_quality', '')::numeric,
          nullif(initial_rating ->> 'time', '')::numeric,
          nullif(initial_rating ->> 'venue', '')::numeric,
          nullif(initial_rating ->> 'packaging', '')::numeric,
          btrim(initial_rating ->> 'notes')
        );
      end if;

    elsif req.request_type = 'update' then
      if nullif(btrim(restaurant_data ->> 'name'), '') is null then
        raise exception 'El nombre de la hamburguesería es obligatorio';
      end if;

      update public.restaurants
      set
        name = restaurant_data ->> 'name',
        description = restaurant_data ->> 'description',
        image_url = restaurant_data ->> 'image_url',
        website_url = restaurant_data ->> 'website_url',
        instagram_url = restaurant_data ->> 'instagram_url',
        address = restaurant_data ->> 'address',
        notes = restaurant_data ->> 'notes'
      where id = req.restaurant_id;

      if not found then
        raise exception 'La hamburguesería ya no existe';
      end if;

      new_restaurant_id := req.restaurant_id;
    end if;

    update public.restaurant_requests
    set
      status = 'approved',
      reviewed_by = auth.uid(),
      reviewed_at = now(),
      reviewer_note = nullif(btrim(coalesce(p_reviewer_note, '')), '')
    where id = req.id;
  else
    new_restaurant_id := req.restaurant_id;

    update public.restaurant_requests
    set
      status = 'rejected',
      reviewed_by = auth.uid(),
      reviewed_at = now(),
      reviewer_note = nullif(btrim(coalesce(p_reviewer_note, '')), '')
    where id = req.id;
  end if;

  return jsonb_build_object(
    'request_id', req.id,
    'status', case when p_approve then 'approved' else 'rejected' end,
    'restaurant_id', new_restaurant_id
  );
end;
$$;

grant execute on function public.review_restaurant_request(bigint, boolean, text)
to authenticated;

-- Vista pública mínima para mostrar nombres de usuarios sin exponer roles.
create or replace view public.public_profiles as
select id, display_name, avatar_url
from public.profiles;

grant select on public.public_profiles to anon;
grant select on public.public_profiles to authenticated;
